version: '3.8'
services:
  twitch-downloader:
    build: .
    container_name: twitch-downloader
    ports:
      - "3000:3000"
    volumes:
      - ./backend/downloads:/app/backend/downloads
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DOWNLOAD_DIR=/app/backend/downloads
      - MAX_CONCURRENT_DOWNLOADS=3