version: '3.8'
services:
  twitch-downloader:
    build: .
    container_name: twitch-downloader
    ports:
      - "8091:8091"
    volumes:
      - ./backend/downloads:/app/backend/downloads
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=8091
      - DOWNLOAD_DIR=/app/backend/downloads
      - MAX_CONCURRENT_DOWNLOADS=3